const ActionTypes = {
    SIGNUP_REQUEST : 'SIGNUP_REQUEST',
    SIGNUP_REQUEST_SUCCESS : 'SIGNUP_REQUEST_SUCCESS',

    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_REQUEST_SUCCESS : 'LOGIN_REQUEST_SUCCESS',
    GMAIL_REQUEST : 'GMAIL_REQUEST',
    GMAIL_REQUEST_SUCCESS:'GMAIL_REQUEST_SUCCESS',
    CHAT_REQUEST : 'CHAT_REQUEST',
    CHAT_REQUEST_SUCCESS : "CHAT_REQUEST_SUCCESS",
    GET_MESSAGE : 'GET_MESSAGE',
    GET_MESSAGE_SUCCESS : 'GET_MESSAGE_SUCCESS',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_REQUEST_SUCCESS:'LOGOUT_REQUEST_SUCCESS'
}

export default ActionTypes;